config/routes.rb
Rails.application.routes.draw do
  ################################################################################
  # Root

  root to: 'home#index'

  ################################################################################
  # API

  namespace :api do
    namespace :v2 do
      resources :rubygems, param: :name, only: [], constraints: { name: Patterns::ROUTE_PATTERN } do
        resources :versions, param: :number, only: :show, constraints: {
          number: /#{Gem::Version::VERSION_PATTERN}(?=\.json\z)|#{Gem::Version::VERSION_PATTERN}/
        }
      end
    end

    namespace :v1 do
      resource :api_key, only: :show do
        put :reset
      end
      resources :profiles, only: :show
      resources :downloads, only: :index do
        get :top, on: :collection
        get :all, on: :collection
      end
      constraints id: Patterns::ROUTE_PATTERN, format: /json|yaml/ do
        get 'owners/:handle/gems',
          to: 'owners#gems',
          as: 'owners_gems',
          constraints: { handle: Patterns::ROUTE_PATTERN },
          format: true

        resources :downloads, only: :show, format: true

        resources :versions, only: :show, format: true do
          member do
            get :reverse_dependencies, format: true
            get 'latest',
              to: 'versions#latest',
              as: 'latest',
              format: true,
              constraints: { format: /json|js/ }
          end

          resources :downloads,
            only: [:index],
            controller: 'versions/downloads',
            format: true do
            collection do
              get :search, format: true
            end
          end
        end
      end

      resources :dependencies,
        only: [:index],
        format: /marshal|json/,
        defaults: { format: 'marshal' }

      # for handling preflight request
      match '/gems/:id' => "rubygems#show", via: :options

      resources :rubygems,
        path: 'gems',
        only: %i[create show index],
        id: Patterns::LAZY_ROUTE_PATTERN,
        format: /json|yaml/ do
        member do
          get :reverse_dependencies
        end
        collection do
          delete :yank, to: "deletions#create"
          put :unyank, to: "deletions#destroy"
        end
        constraints rubygem_id: Patterns::ROUTE_PATTERN do
          resource :owners, only: %i[show create destroy]
        end
      end

      resource :activity, only: [], format: /json|yaml/ do
        collection do
          get :latest
          get :just_updated
        end
      end

      resource :search, only: :show

      resources :web_hooks, only: %i[create index] do
        collection do
          delete :remove
          post :fire
        end
      end
    end
  end

  get '/versions' => 'api/compact_index#versions'
  get '/info/:gem_name' => 'api/compact_index#info', as: :info,
      constraints: { gem_name: Patterns::ROUTE_PATTERN }
  get '/names' => 'api/compact_index#names'
  ################################################################################
  # API v0

  scope controller: 'api/deprecated', action: 'index' do
    get 'api_key'
    put 'api_key/reset'

    post 'gems'
    get 'gems/:id.json'

    scope path: 'gems/:rubygem_id' do
      put 'migrate'
      post 'migrate'
      get 'owners(.:format)'
      post 'owners(.:format)'
      delete 'owners(.:format)'
    end
  end

  ################################################################################
  # UI
  scope constraints: { format: :html }, defaults: { format: 'html' } do
    resource :search, only: :show do
      get :advanced
    end
    resource :dashboard, only: :show, constraints: { format: /html|atom/ }
    resources :profiles, only: :show
    resource :profile, only: %i[edit update] do
      member do
        get :delete
        delete :destroy, as: :destroy
      end
    end
    resources :stats, only: :index
    resource :news, path: 'news', only: [:show] do
      get :popular, on: :collection
    end

    resources :rubygems,
      only: %i[index show edit update],
      path: 'gems',
      constraints: { id: Patterns::ROUTE_PATTERN, format: /html|atom/ } do
      resource :subscription,
        only: %i[create destroy],
        constraints: { format: :js },
        defaults: { format: :js }
      resources :versions, only: %i[show index]
      resources :reverse_dependencies, only: %i[index]
    end
  end

  ################################################################################
  # Clearance Overrides and Additions

  resource :email_confirmations, only: %i[new create] do
    get 'confirm/:token', to: 'email_confirmations#update', as: :update
    patch 'unconfirmed'
  end

  resource :session, only: %i[create destroy]

  resources :passwords, only: %i[new create]

  resources :users, only: %i[new create] do
    resource :password, only: %i[create edit update]
  end

  ################################################################################
  # Internal Routes

  namespace :internal do
    get 'ping' => 'ping#index'
    get 'revision' => 'ping#revision'
  end

  unless Clearance.configuration.allow_sign_up?
    get '/sign_up' => 'users#disabled_signup'
  end
end

app/controllers/api/v1/searches_controller.rb
class Api::V1::SearchesController < Api::BaseController
  skip_before_action :verify_authenticity_token
  before_action :set_page, only: :show

  def show
    @rubygems = Rubygem.legacy_search(params.require(:query)).with_versions.paginate(page: @page)
    respond_to do |format|
      format.json { render json: @rubygems }
      format.yaml { render yaml: @rubygems }
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_page, :limit_page, only: :show
  # Limit max page as ES result window is upper bounded by 10_000 records
  MAX_PAGE = 100

  def show
    return unless params[:query] && params[:query].is_a?(String)
    @error_msg, @gems = Rubygem.search(params[:query], es: es_enabled?, page: @page)
    @exact_match = Rubygem.name_is(params[:query]).with_versions.first
    redirect_to rubygem_path(@exact_match) if @exact_match && @gems.size == 1
  end

  def advanced
  end

  private

  def limit_page
    render_404 if @page > MAX_PAGE
  end

  def es_enabled?
    true
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
  def es_suggestions(gems)
    return false if gems.size >= 1
    return false unless gems.respond_to?(:response)
    suggestions = gems.response['suggest']
    return false if suggestions.blank?
    return false if suggestions['suggest_name'].blank?
    return false if suggestions['suggest_name'][0]['options'].empty?
    suggestions.map { |_k, v| v.first['options'] }.flatten.map { |v| v['text'] }.uniq
  end

  def aggregation_match_count(aggregration, field)
    count = aggregration['buckets'][field]['doc_count']
    if count > 0
      path = search_path(params: { query: "#{field}:#{params[:query]}" })
      link_to "#{field.capitalize} (#{count})", path, class: 't-link--black'
    end
  end

  def aggregation_week_count(aggregration)
    count = aggregration['buckets'][1]['doc_count']
    if count > 0
      week_ago = (Time.zone.today - 7.days).to_s(:db)
      path = search_path(params: { query: "#{params[:query]} AND updated:[#{week_ago} TO *}" })
      link_to "Updated last week (#{count})", path, class: 't-link--black'
    end
  end

  def aggregation_month_count(aggregration)
    count = aggregration['buckets'][0]['doc_count']
    if count > 0
      month_ago = (Time.zone.today - 30.days).to_s(:db)
      path = search_path(params: { query: "#{params[:query]} AND updated:[#{month_ago} TO *}" })
      link_to "Updated last month (#{count})", path, class: 't-link--black'
    end
  end
end

app/views/searches/_aggregations.html.erb
<% if gems.respond_to?(:response) && aggregations = gems.response['aggregations'] %>
  <div class="aggregations">
    Filter:
    <%= aggregation_match_count aggregations['matched_field'], 'name' %>
    <%= aggregation_match_count aggregations['matched_field'], 'description' %>
    <%= aggregation_match_count aggregations['matched_field'], 'summary' %>
    <%= aggregation_week_count aggregations['date_range'] %>
    <%= aggregation_month_count aggregations['date_range'] %>
  </div>
<% end %>

app/views/searches/advanced.html.erb
<% @title = t("advanced_search") %>

<div class="home__search-wrap">
  <%= form_tag search_url, id: "advanced-search", method: :get do %>
    <%= search_field_tag :query, params[:query], placeholder: t("layouts.application.header.search_gem").html_safe, autofocus: current_page?(root_url), id: "home_query", class: "home__search" %>
    <%= label_tag :home_query do %>
      <span class="t-hidden"><%= t("layouts.application.header.search_gem").html_safe %></span>
    <% end %>
    <%= submit_tag "⌕", name: nil, class: "home__search__icon" %>
  <% end %>

  <dl id="search-fields">
    <dt><%= label_tag :name, t(".name"), class: "form__label" %></dt>
    <dd><%= text_field_tag :name, "", placeholder: "active OR action", class: "form__input"%></dd>

    <dt><%= label_tag :summary, t(".summary"), class: "form__label" %></dt>
    <dd><%= text_field_tag :summary, "", placeholder: "ORM, NoSQL", class: "form__input"%></dd>

    <dt><%= label_tag :description, t(".description"), class: "form__label" %></dt>
    <dd><%= text_field_tag :description, "", placeholder: "associations AND validations", class: "form__input"%></dd>

    <dt><%= label_tag :downloads, t(".downloads"), class: "form__label" %></dt>
    <dd><%= text_field_tag :downloads, "", placeholder: ">20000", class: "form__input"%></dd>

    <dt><%= label_tag :updated, t(".updated"), class: "form__label" %></dt>
    <dd><%= text_field_tag :updated, "", placeholder: ">#{1.week.ago.strftime('%F')}", class: "form__input"%></dd>
  </dl>
</div>

app/views/searches/show.html.erb
<% @title = "search" %>

<% if @error_msg %>
  <div class="errorExplanation">
    <p><%= @error_msg %></p>
  </div>
<% end %>
<%= link_to t("advanced_search"), advanced_search_path, class: "t-link--gray t-link--has-arrow" %>
<% if @gems %>
  <% @subtitle = t('.subtitle', :query => content_tag(:em, h(params[:query]))) %>

  <% if @exact_match %>
    <header class="gems__header">
      <p class="gems__meter"><%= t '.exact_match' %></p>
    </header>
    <% content_for :head do %>
      <link rel="prerender prefetch" href="<%= rubygem_url(@exact_match) %>">
    <% end %>
    <%= render partial: 'rubygems/rubygem', object: @exact_match %>
  <% end %>

  <header class="gems__header push">
    <p class="gems__meter"><%= page_entries_info(@gems, :entry_name => 'gem', :model => 'gem').html_safe %></p>
  </header>

  <%= render partial: 'aggregations', locals: { gems: @gems } %>

  <% if suggestions = es_suggestions(@gems)  %>
    <div class='search__suggestions'>
      <p>
        Maybe you mean
        <%= suggestions.map do |term|
          link_to term, search_path(params: { query: term }), only_path: true
        end.to_sentence(last_word_connector: ' or ').html_safe %>?
      </p>
    </div>
  <% end %>

  <% if @gems.present? %>
    <%= render partial: 'rubygems/rubygem', collection: @gems %>
    <%= will_paginate @gems %>
  <% end %>
<% end %>